services:
  - type: web
    name: talent-track-backend
    runtime: node
    region: oregon
    plan: starter
    repo: https://github.com/tonytega/talent-track.git
    branch: master
    autoDeployTrigger: commit
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health

    envVars:
      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_ANON_KEY
        sync: false

      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      - key: SUPABASE_DB_URL
        sync: false

      - key: GEMINI_API_KEY
        sync: false